config/routes.rb
GoodReads::Application.routes.draw do

  resources :books

  match "/help", to: "static_pages#help"
  match "/about", to: "static_pages#about"
  match "/contact", to: "static_pages#contact"

  root :to => "static_pages#home"

  resources :spam_domain, only: [:create, :index]
  delete "/spam_domain", to: "spam_domain#destroy", as: :delete_spam

  resources :users
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :reviews, only: [:create, :update, :destroy]
  resources :user_book_statuses, only: [:create, :update, :destroy]
  resources :my_books, only: [:index]

  delete "/sign_out", to: "user_sessions#destroy", as: :sign_out
  get "/sign_in", to: "user_sessions#new", as: :sign_in

  get "/confirm_user/:id/:token", to: "users#confirm", as: :email_confirmation

end

app/models/book.rb
class Book < ActiveRecord::Base
  #   attr_accessible :author, :cover, :isbn_number, :language,
  #     :published_year, :publisher, :synopsis,
  #     :title, :average_rating, :rating_count

  has_many :reviews, foreign_key: "book_id", dependent: :destroy, autosave: true
  has_many :user_book_statuses, foreign_key: :book_id, dependent: :destroy
  has_many :users, through: :reviews
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :require_admin_privileges, only: [:new, :create, :update, :destroy, :edit]
  before_filter :require_user, only: [:show]
  before_filter :find_book_by_params, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    # @book = Book.all

    respond_to do |format|
      format.html do # index.html.erb
        @books = Book.paginate(:page => params[:page])
      end
      format.json do
        @books = Rails.cache.fetch("books") {
          Book.all
        }
        if params[:page] && params[:per_page]
          # @books1 = Book.page(params[:page]).per(params[:per_page])
          m = params[:page].to_i
          n = params[:per_page].to_i

          s_idx = ((m - 1) * n)
          e_idx = (m * n) - 1

          total_pages = (@books.length / n.to_f).ceil
          @books = @books[s_idx..e_idx]

          jsonObj = {
            'meta': {'total_pages': total_pages},
            'books': @books.as_json,
          }

          render json: jsonObj
        else
          render json: {'books': @books.as_json}
        end
      end
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @review_items = @book.reviews.paginate(page: params[:page]).preload(:user)
    @status_categories = StatusCategory.all
    @current_status = current_user.user_book_statuses.find_by_book_id(@book)
    @is_review_not_present = @book.reviews.find_by_user_id(current_user).nil?

    @relationship = @book.reviews.find_by_user_id(current_user.id)

    if @relationship.nil?
      @relationship = Review.new
      @relationship.user = current_user
      @relationship.book = @book
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update_attributes(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private

  # Use this method to whitelist the permissible parameters. Example:
  # params.require(:person).permit(:name, :age)
  # Also, you can specialize this method with per-user checking of permissible attributes.
  def book_params
    params.require(:book).permit(:author, :cover, :isbn_number, :language, :published_year, :publisher, :synopsis, :title)
  end
end

app/helpers/books_helper.rb
module BooksHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = {size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)

    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/books/_book_view.html.erb
<div class='span3'>
    <div style="margin-top: 17px"><%= image_tag @book.cover, alt: @book.title %></div>

    <%= render 'bookmark_dropdown' %>
</div>

<div class='span9'>
    <div class="">
    <h2 style="text-align: left;"><%= @book.title %></h2>
    </div>

    <div class="">
    <h5>by <%= @book.author %></h5>
    </div>

    <div class="synopsis">
    <p><%= @book.synopsis %></p>
    </div>

    <hr>
    <p>
        <b>Average Rating:</b>
        <%= '%.2f' % @book.average_rating %>
    </p>

    <p>
        <b>Published year:</b>
        <%= @book.published_year %>
    </p>

    <p>
        <b>Language:</b>
        <%= @book.language %>
    </p>

    <p>
        <b>Publisher:</b>
        <%= @book.publisher %>
    </p>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#reviewModal">
        <% if @is_review_not_present %>
          Add a Review
        <% else %>
          Update Review
        <% end %>
    </button>
</div>

<%= render "review_modal" %>

app/views/books/_bookmark_dropdown.html.erb
<!-- Example split danger button -->
<div class="btn-group" id="bookmark-dd-group">

    <% if @current_status.nil? %>
        <%= link_to StatusCategory.first.name, user_book_statuses_path(status_id: 1, book_id: @book.id), method: :post, class: 'btn btn-success', id: 'bookmark-dd-btn' %>
    <% else %>
        <button type="button" class="btn btn-secondary disabled" id="bookmark-dd-btn"><%= @current_status.status_category.name %></button>
    <% end %>
    <button type="button" class="btn btn-success dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="sr-only"><b class="caret"></b></span>
    </button>
    <div class="dropdown-menu">
        <% if @current_status.nil? %>
            <!-- Creating new status relationship-->
            <% @status_categories.each do |category| %>
                <%= link_to category.name, user_book_statuses_path(status_id: category.id, book_id: @book.id), method: :post, class: "dropdown-item" %>
            <% end %>
        <% else %>
            <!-- Updating status-->
            <% @status_categories.delete_at(@status_categories.find_index(@current_status.status_category)) %>
            <% @status_categories.each do |category| %>
                <%= link_to category.name, user_book_status_path(id: @current_status.id,status_id: category.id), method: :put, class: "dropdown-item" %>
            <% end %>
        <% end  %>
    </div>

</div>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>

  <%= render 'shared/errors', object: @book %>

  <div class="container">
    <div class="row">

      <!-- 1st Half of the form -->
      <div class="span6">
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control'%>
        </div>
        <div class="form-group">
          <%= f.label :isbn_number %>
          <%= f.text_field :isbn_number, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :author %>
          <%= f.text_field :author, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :synopsis %>
          <%= f.text_field :synopsis, class: 'form-control' %>
        </div>
      </div>

      <!-- 2nd Half of the form -->
      <div class="span6">
        <div class="form-group">
          <%= f.label :published_year %>
          <%= f.text_field :published_year, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :language %>
          <%= f.text_field :language, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :cover %>
          <%= f.text_field :cover, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :publisher %>
          <%= f.text_field :publisher, class: 'form-control' %>
        </div>
      </div>

    </div>

    <div class="">
      <div class="actions">
        <%= f.submit 'Add', class: 'btn btn-success btn-lg'%>
      </div>
    </div>
  </div>
<% end %>

app/views/books/_review_item.html.erb
<li id="<%= review_item.id %>">
    <div class="container">
        <div class="row">
            <div class="col-sm-2 span2">
                <%= link_to gravatar_for(review_item.user), review_item.user %>
            </div>
            
            <div class="col-sm-8 span8">
                <h4><%= link_to review_item.user.name, review_item.user %></h4>

                <b>Rating: </b><%= review_item.rating %>
                <br>

                <p><%= review_item.review %></p>
            </div>

            <div class="col-sm-2 span2">
                <% if current_user?(review_item.user) %>
                    <%= link_to "delete", review_item, method: :delete,
                                     data: { confirm: "Are you sure?" },
                                     title: review_item.review %>
                <% end %>
            </div>
        </div>
    </div>

</li>

app/views/books/_review_modal.html.erb
<!-- Modal -->
<div id="reviewModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Review</h3>
  </div>
  <div class="modal-body">

    <%= form_for(@relationship) do |f| %>
      <%= render 'shared/errors', object: f.object %>

      <div class="container">
        <div class="">
            <div class="span1">
                <%= image_tag @book.cover, alt: @book.title, width: "50px" %>
            </div>

            <div class="span8">
                <h4><%= @book.title %></h4>
                <h5>by <%= @book.author %></h5>
            </div>
        </div>
      </div>

      <hr>
      <input type="hidden" class="rating">
      
      <%= f.label :rating %>
      <%= f.text_field :rating, class: "text-field" %>

      <%= f.label :review %>
      <%= f.text_area :review, class: "text-area" %>

      <%= f.hidden_field :book_id %>
      <%= f.hidden_field :user_id %>

        <br/>
      <%= f.submit "Save", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <!--<button class="btn btn-primary">Save changes</button>-->
  </div>
</div>

app/views/books/_reviews.html.erb
<% if @review_items.any? %>
  <ul class="reviews">
    <%= render partial: 'review_item', collection: @review_items %>
  </ul>
  <%= will_paginate @review_items %>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="page-header"><h1>Listing books</h1></div>

<%= will_paginate %>
<table class="table table-hover">
  <tr>
    <th>Cover</th>
    <th>Title</th>
    <th>Isbn number</th>
    <th>Author</th>
    <th>Synopsis</th>
    <th>Published year</th>
    <th>Language</th>
    <th>Publisher</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= link_to image_tag(book.cover, alt: book.title, width: '60px'), book.cover %></td>
    <td><%= link_to book.title, book %></td>
    <td class='large-text'><%= book.isbn_number %></td>
    <td><%= book.author %></td>
    <td class='large-text'><%= book.synopsis %></td>
    <td><%= book.published_year %></td>
    <td><%= book.language %></td>
    <td><%= book.publisher %></td>
    <td><%= link_to 'Show', book %></td>
    <% if current_user.admin? %>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<% if current_user.admin? %>
  <br/>
  <%= link_to 'New Book', new_book_path %>
<% end %>

<%= will_paginate %>

app/views/books/new.html.erb
<div class='page-header'><h1>New book</h1></div>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class='container'>
  <div class='row'>
    <%= render 'book_view' %>
  </div>

  <div class="">
    <h3>Reviews (<%= @review_items.count %>)</h3>
    <%= render 'reviews' %>
  </div>
</div>