config/routes.rb
GoodReads::Application.routes.draw do

  resources :books

  match "/help", to: "static_pages#help"
  match "/about", to: "static_pages#about"
  match "/contact", to: "static_pages#contact"

  root :to => "static_pages#home"

  resources :spam_domain, only: [:create, :index]
  delete "/spam_domain", to: "spam_domain#destroy", as: :delete_spam

  resources :users
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :reviews, only: [:create, :update, :destroy]
  resources :user_book_statuses, only: [:create, :update, :destroy]
  resources :my_books, only: [:index]

  delete "/sign_out", to: "user_sessions#destroy", as: :sign_out
  get "/sign_in", to: "user_sessions#new", as: :sign_in

  get "/confirm_user/:id/:token", to: "users#confirm", as: :email_confirmation

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params.to_h)
    saved = @user_session.save

    respond_to do |format|
      format.html do
        if saved
          redirect_to root_url, notice: "Welcome Back!"
        else
          render :new
        end
      end

      format.json do
        json_obj = {}

        if saved
          json_obj["error"] = false
          json_obj["status"] = {}
          json_obj["user"] = @user_session
          render json: json_obj
        else
          json_obj["error"] = true
          json_obj["status"] = {
            "messages": @user_session.errors.full_messages,
          }
          json_obj["user"] = @user_session
          render json: json_obj
        end
      end
    end
  end

  def destroy
    current_user_session.destroy
    flash[:success] = "Logged Out Successfully!"
    redirect_to root_url
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password, :remember_me)
  end
end

app/views/user_sessions/new.html.erb
<div class="page-header"><h1>Sign In</h1></div>
<div class="row">
  <div class="span8">
    <%= form_for @user_session do |f| %>
      <%= render 'shared/errors', object: @user_session %>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :remember_me %>
        <%= f.check_box :remember_me %>
      </div>
      <br/>

      <%= f.submit "Log in!", class: 'btn btn-primary btn-lg' %></br>
      <%= link_to 'Forgot your password?', new_password_reset_path, class: '' %>
    <% end %>
  </div>
</div>