config/routes.rb
GoodReads::Application.routes.draw do

  resources :books

  match "/help", to: "static_pages#help"
  match "/about", to: "static_pages#about"
  match "/contact", to: "static_pages#contact"

  root :to => "static_pages#home"

  resources :spam_domain, only: [:create, :index]
  delete "/spam_domain", to: "spam_domain#destroy", as: :delete_spam

  resources :users
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :reviews, only: [:create, :update, :destroy]
  resources :user_book_statuses, only: [:create, :update, :destroy]
  resources :my_books, only: [:index]

  delete "/sign_out", to: "user_sessions#destroy", as: :sign_out
  get "/sign_in", to: "user_sessions#new", as: :sign_in

  get "/confirm_user/:id/:token", to: "users#confirm", as: :email_confirmation

end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <small>
    Clone
    by Freshworks
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help",    help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://www.goodreads.com/">Original</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top" id="navbar">
  <div class="navbar-inner navbar-default" id="navbar">
    <div class="container">
      <%= link_to "Good Reads", root_url, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_url %></li>
          <% if current_user %>
            <% if current_user.admin? %>
              <li><%= link_to 'New Book', new_book_path %></li>
              <li><%= link_to 'Spams', spam_domain_index_path %></li>
            <% end %>
            <li><%= link_to 'Explore', books_path %></li>
            <li><%= link_to 'My Books', my_books_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "About",   about_path %></li>

            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= gravatar_for current_user, size: 20 %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li class="disabled" style="text-align: left;padding-left: 20px;"><%= current_user.name %></li>
                <li class="divider"></li>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", sign_out_path, method: :delete %>
                </li>
              </ul>
            </li>
            
          <% else %>
            <li><%= link_to 'Register', new_user_path %></li>
            <li><%= link_to 'Sign In', sign_in_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>

      <%= yield %>
      <!-- <%= debug(params) if Rails.env.development? %> -->
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>